spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oauth2?useSSL=false&useUnicode=true&useLegacyDatetimeCode=false&serverTimezone=Turkey
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      file-size-threshold: 2KB
      max-request-size: 256MB
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
server:
  port: 8081